[package]
name = "swaggapi-macro"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "~2", features = ["full"] }
quote = "~1"
proc-macro2 = "~1"
